[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Not a Graphical Game"
version = "0.0.1"
requires-python = ">=3.7"

[project.optional-dependencies]
test = [
  "pytest",
  "uncertainties"
]
